#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.{build}                 # You can use {branch} to, for example

branches:
  only:
  - master
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# fetch repository as zip archive
shallow_clone: true                 # default is "false"


# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
# platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


build:
  parallel: true                  # enable MSBuild parallel builds
  project: src/Heijden.Dns.sln        # path to Visual Studio solution or project
#  publish_nuget: true             # package projects with .nuspec files and push to artifacts (does not work)
#  publish_nuget_symbols: true     # generate and publish NuGet symbol packages (does not work)

  # MSBuild verbosity level
  verbosity: normal # quiet|minimal|normal|detailed


# scripts to run before build
before_build:
  - nuget restore src\Heijden.Dns.sln

# to run your custom scripts instead of automatic MSBuild
build_script:
 - msbuild "/p:Configuration=Release" "src\Heijden.Dns.Portable\Heijden.Dns.Portable.csproj"

# scripts to run after build
after_build:
 - nuget pack Heijden.Dns.Portable.nuspec -Version %appveyor_build_version%
 - appveyor PushArtifact Heijden.Dns.Portable.%appveyor_build_version%.nupkg
#  - powershell nuget\pack.ps1
#http://help.appveyor.com/discussions/questions/1438-not-sure-how-to-publish-to-the-official-nuget-server

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#test:
#  assemblies:
#    - Heijden.Dns.Tests.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
   - path: 'Heijden.Dns.Portable.%appveyor_build_version%.nupkg'

#  - path: src\Heijden.Dns.Portable\bin\$(configuration)
#    name: Heijden.Dns.Portable Binaries

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off

deploy:
- provider: NuGet
  api_key:
    secure: BmdYyUUC00I8rs3Z7OuwI8mr7QLAAxP5GYa7qWBQfx0eD8oxGOhqPPZQK8KMNX4Y
  skip_symbols: true
